CREATE TABLE "wishlists"(
    "id" INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "user_id" INT NOT NULL ,
    "item_id" INT NOT NULL ,
    CONSTRAINT "fk_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "fk_item" FOREIGN KEY ("item_id") REFERENCES "items" ("id") ON DELETE SET NULL ON UPDATE CASCADE
)